stages:
  - deploy

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - "command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
    # - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    # - chmod 644 ~/.ssh/config
  script:
    - scp deploy.sh $SERVER_USER@$SERVER_IP:~/app/
    - scp docker-compose.yml $SERVER_USER@$SERVER_IP:~/app/
    - scp Dockerfile $SERVER_USER@$SERVER_IP:~/app/
    - |
      ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
        cd ~/app
        chmod +x deploy.sh
        DB_USER=${DB_USER} DB_PASSWORD=${DB_PASSWORD} DB_NAME=${DB_NAME} DB_PORT=${DB_PORT} APP_PORT=${APP_PORT} ./deploy.sh
      "
  only:
    - main